ALTER TYPE "MessageTemplateKey" ADD VALUE 'WAITLIST_JOINED';
ALTER TYPE "MessageTemplateKey" ADD VALUE 'WAITLIST_PROMOTED';
ALTER TYPE "MessageTemplateKey" ADD VALUE 'REGISTRATION_CANCELLED';
ALTER TYPE "MessageTemplateKey" ADD VALUE 'REGISTRATION_CONTACT_UPDATED';
ALTER TYPE "MessageTemplateKey" ADD VALUE 'PAYMENT_RECEIPT';
