import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

const landingMocks = vi.hoisted(() => ({
  getPublicEventLanding: vi.fn(),
}));

vi.mock("@/modules/events/public-repository", () => ({
  getPublicEventLanding: landingMocks.getPublicEventLanding,
}));
// The page reads auto info cards only for club events (#651); this file's events are not.
vi.mock("@/modules/event-info-cards/repository", () => ({
  getAutoEventInfoCards: vi.fn(),
}));
vi.mock("next/navigation", () => ({
  notFound: vi.fn(),
}));
// The page sanitizes custom HTML (#816) through a server-only module.
vi.mock("server-only", () => ({}));

import PublicEventPage from "@/app/(public)/events/[eventSlug]/page";

const landing = {
  event: {
    slug: "public-retreat",
    name: "Public Retreat",
    startsAt: "2026-08-14T21:00:00.000Z",
    endsAt: "2026-08-16T17:00:00.000Z",
    timezone: "America/Chicago",
    location: "Fictitious Conference Center",
    capacity: 100,
    supportContact: "events@example.test",
    dateLabel: "August 14 – 16, 2026",
    timeLabel: "Friday, 4:00 PM CDT – Sunday, 12:00 PM CDT",
  },
  lifecycle: {
    phase: "OPEN",
    state: "OPEN",
    statusLabel: "Registration open",
    detail: "Choose the form that matches your registration.",
    ctaLabel: "Start registration",
    ctaEnabled: true,
    ended: false,
    heroTagline: "Everything you need to choose the right registration path.",
    formsHeading: "Choose how you’re registering",
    emptyForms: {
      title: "Registration forms are being prepared",
      body: "Event details are available now.",
    },
    availability: { heading: "Registration open", body: "96 spots currently remain." },
    remainingSpots: 96,
  },
  forms: [],
  // The page filters these by kind, so an empty list is the neutral case.
  contentSections: [],
  links: {
    detailsUrl: "https://imsda.org/events/",
    supportUrl: "https://imsda.org/contact/",
  },
  announcements: [{
    id: "announcement-db-id-is-not-public",
    audience: { type: "ALL_ATTENDEES" },
    title: "Arrival information",
    body: "Use the south entrance. <script>alert('unsafe')</script>",
    placement: "HOME_BANNER",
    placementLabel: "Featured notice",
    priority: "IMPORTANT",
    priorityLabel: "Important",
    publishedAt: "2026-07-22T13:30:00.000Z",
    publishedLabel: "Jul 22, 2026, 8:30 AM CDT",
    isFeatured: true,
  }],
};



// The five section kinds that existed before #816 must render exactly as they
// did. The snapshot file was generated from the code before the new blocks
// existed (commit 0bbc660) and is never regenerated by this change.
const existingSections = [
  { id: "s1", kind: "RICH_TEXT", title: "What to bring", body: "Read this first.\n<b>not bold</b>\n- Towel\n- Flashlight", placement: "PUBLIC_PAGE", tone: null, items: [], isPublished: true, links: [] },
  { id: "s2", kind: "RESOURCE_LINKS", title: "Downloads", body: "", placement: "PUBLIC_PAGE", tone: null, items: [], isPublished: true, links: [{ label: "Packing guide", description: "PDF checklist", url: "https://example.test/packing.pdf", assetId: null }] },
  { id: "s3", kind: "NOTICE", title: "Registration deadline", body: "Register by the closing date.\n- Bring your form", placement: "BOTH", tone: "DEADLINE", items: [], isPublished: true, links: [{ label: "Email the office", description: "", url: "mailto:office@example.org", assetId: null }] },
  { id: "s4", kind: "STEPS", title: "How to register", body: "", placement: "PUBLIC_PAGE", tone: null, items: [{ title: "Choose a form", text: "Pick the one that matches you." }, { title: "Pay", text: "" }], isPublished: true, links: [] },
  { id: "s5", kind: "CHECKLIST", title: "Have ready", body: "", placement: "BOTH", tone: null, items: [{ title: "Roster", text: "" }, { title: "Payment method", text: "" }], isPublished: true, links: [] },
];

describe("existing sections render exactly as before (#816)", () => {
  it("renders the public page for the five original kinds identically to the pre-blocks markup", async () => {
    landingMocks.getPublicEventLanding.mockResolvedValue({ ...landing, announcements: [], contentSections: existingSections });
    const markup = renderToStaticMarkup(await PublicEventPage({
      params: Promise.resolve({ eventSlug: "public-retreat" }),
    }));
    await expect(markup).toMatchFileSnapshot("./snapshots/event-page-existing-sections.html");
    // Without a banner the page keeps its own h1, and no block wrapper appears.
    expect(markup).toContain("<h1>Public Retreat</h1>");
    expect(markup).not.toContain("event-blocks");
    expect(markup).not.toContain("event-hero-banner");
  });
});
